version: '3'

services:
  influxdb:
    image: influxdb:1.3
    ports:
      - "8086:8086"
      - "8083:8083"
    volumes:
      - /data/influxdb:/var/lib/influxdb
    networks:
      - influxdbnet

  grafana:
    image: grafana/grafana
    ports:
      - "5602:3000"
    depends_on:
      - influxdb
    volumes:
      - /data/grafana:/var/lib/grafana
    networks:
      - influxdbnet

  chronograf:
    image: chronograf
    ports:
      - "8888:8888"
    depends_on:
      - influxdb
    command: "--influxdb-url=http://influxdb:8086"
    volumes:
      - /data/chronograf:/var/lib/chronograf
    networks:
      - influxdbnet

networks:
  influxdbnet:
    driver: overlay
    ipam:
      driver: default
      config:
        - subnet: 172.28.0.0/16
