version: '2'

services:
  elasticsearch:
    build: elasticsearch/
    container_name: elastic-search
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      ES_JAVA_OPTS: "-Xms1g -Xmx1g"
    networks:
      - elastic
    volumes:
      - /data/elasticsearch:/usr/share/elasticsearch/data
  kibana:
    build: kibana/
    container_name: elastic-kibana
    volumes:
      - ./kibana/config/:/usr/share/kibana/config/
    ports:
      - "5601:5601"
    networks:
      - elastic
    depends_on:
      - elasticsearch

networks:
  elastic:
    driver: bridge
