version: '3'

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.0.0
    environment:
      ES_JAVA_OPTS: "-Xms1g -Xmx1g"
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data
    ports:
      - 9200
      - 9300
    networks:
      - elasticnet
  kibana:
    image: docker.elastic.co/kibana/kibana-oss:6.0.0
    volumes:
      - kibana-data:/usr/share/kibana/config
    ports:
      - "5601:5601"
    networks:
      - elasticnet
    depends_on:
      - elasticsearch

volumes:
  elasticsearch-data:
  kibana-data:

networks:
  elasticnet:
    driver: overlay
    ipam:
      driver: default
      config:
        - subnet: 172.28.0.0/16
